Yukbisaaaaaa

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -104,17 +104,19 @@ jobs:
                     echo "✅ Run ID yang berhasil diambil: $RUN_ID"
 
       - name: Build Docker Model
-        env:
-          MLFLOW_TRACKING_URI: https://naemaaa:${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/naemaaa/Sepsis-ICU-MLflow.mlflow
-          MLFLOW_TRACKING_USERNAME: naemaaa
-          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
         run: |
           echo "=== Build Docker Image ==="
           echo "Using run_id: ${{ steps.get_run_id.outputs.run_id }}"
-          mlflow models build-docker \
-            -m "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
-            --name sepsis-icu-model \
-            --enable-mlserver
+          
+          # Retry 4 kali dengan jeda (karena DagsHub sering 500)
+          for i in {1..4}; do
+            echo "Attempt $i/4 ..."
+            mlflow models build-docker \
+              -m "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
+              --name sepsis-icu-model \
+              --enable-mlserver && break || echo "Gagal attempt $i, tunggu 15 detik..."
+            sleep 15
+          done
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
